name: 'Release tag'
description: 'Release verion to npm from git tags'
author: 'Rabbit <yfhj1990@hotmail.com>'
inputs:
  context:
    description: 'Bundle context, default to current directory'
    default: '.'
  name:
    description: 'Release name'
  body:
    description: 'Release body'
runs:
  using: 'node12'
  main: '../dist/release-tag.js'