name: 'publish-npm'
description: 'Publish npm on release event'
author: 'Rabbit <yfhj1990@hotmail.com>'
inputs:
  github_package:
    description: 'Also publish to github package'
    default: true
runs:
  using: 'node12'
  main: '../dist/publish-npm.js'
