name: 'Release master branch'
description: 'Release @master tag to npm from master branch'
author: 'Rabbit <yfhj1990@hotmail.com>'
inputs:
  context:
    description: 'Bundle context, default to current directory'
    default: '.'
  tag:
    description: 'Publish tag'
    default: 'master'
  gh-package:
    description: 'Also publish to GitHub package registry'
    default: true
runs:
  using: 'node12'
  main: '../dist/release-master.js'