name: Bot on issue comment

on: 
  issue_comment:
    types:
      - created
jobs:
  commented:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: HairyRabbit/actions/bot@latest
        with:
          users: HairyRabbit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
