name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://registry.npmjs.org'
    - uses: HairyRabbit/actions/release-tag@latest
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
